language: go

before_install:
  - sudo apt-get install -y mecab mecab-ipadic-utf8 libmecab-dev
  - export CGO_LDFLAGS="`mecab-config --libs`"
  - export CGO_CFLAGS="-I`mecab-config --inc-dir`"

script: go test
