[package]
name = "ke2daira"
version = "2.0.0"
authors = ["Ryuichi Ueda <ryuichiueda@gmail.com>"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mecab = "*"
