[package]
name = "ke2daira"
version = "2.1.0"
edition = "2021"
authors = ["Ryuichi Ueda <ryuichiueda@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mecab = "*"
